# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = $(CURDIR)

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = $(CURDIR)

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start $(CMAKE_BINARY_DIR)/CMakeFiles $(CMAKE_BINARY_DIR)/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f $(CMAKE_BINARY_DIR)/CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start $(CMAKE_BINARY_DIR)/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named phyDBSCAN

# Build rule for target.
phyDBSCAN: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 phyDBSCAN
.PHONY : phyDBSCAN

# fast build rule for target.
phyDBSCAN/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phyDBSCAN.dir/build.make CMakeFiles/phyDBSCAN.dir/build
.PHONY : phyDBSCAN/fast

src/ARI.o: src/ARI.cpp.o
.PHONY : src/ARI.o

# target to build an object file
src/ARI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phyDBSCAN.dir/build.make CMakeFiles/phyDBSCAN.dir/src/ARI.cpp.o
.PHONY : src/ARI.cpp.o

src/ARI.i: src/ARI.cpp.i
.PHONY : src/ARI.i

# target to preprocess a source file
src/ARI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phyDBSCAN.dir/build.make CMakeFiles/phyDBSCAN.dir/src/ARI.cpp.i
.PHONY : src/ARI.cpp.i

src/ARI.s: src/ARI.cpp.s
.PHONY : src/ARI.s

# target to generate assembly for a file
src/ARI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phyDBSCAN.dir/build.make CMakeFiles/phyDBSCAN.dir/src/ARI.cpp.s
.PHONY : src/ARI.cpp.s

src/Clustering.o: src/Clustering.cpp.o
.PHONY : src/Clustering.o

# target to build an object file
src/Clustering.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phyDBSCAN.dir/build.make CMakeFiles/phyDBSCAN.dir/src/Clustering.cpp.o
.PHONY : src/Clustering.cpp.o

src/Clustering.i: src/Clustering.cpp.i
.PHONY : src/Clustering.i

# target to preprocess a source file
src/Clustering.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phyDBSCAN.dir/build.make CMakeFiles/phyDBSCAN.dir/src/Clustering.cpp.i
.PHONY : src/Clustering.cpp.i

src/Clustering.s: src/Clustering.cpp.s
.PHONY : src/Clustering.s

# target to generate assembly for a file
src/Clustering.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phyDBSCAN.dir/build.make CMakeFiles/phyDBSCAN.dir/src/Clustering.cpp.s
.PHONY : src/Clustering.cpp.s

src/FileIO.o: src/FileIO.cpp.o
.PHONY : src/FileIO.o

# target to build an object file
src/FileIO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phyDBSCAN.dir/build.make CMakeFiles/phyDBSCAN.dir/src/FileIO.cpp.o
.PHONY : src/FileIO.cpp.o

src/FileIO.i: src/FileIO.cpp.i
.PHONY : src/FileIO.i

# target to preprocess a source file
src/FileIO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phyDBSCAN.dir/build.make CMakeFiles/phyDBSCAN.dir/src/FileIO.cpp.i
.PHONY : src/FileIO.cpp.i

src/FileIO.s: src/FileIO.cpp.s
.PHONY : src/FileIO.s

# target to generate assembly for a file
src/FileIO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phyDBSCAN.dir/build.make CMakeFiles/phyDBSCAN.dir/src/FileIO.cpp.s
.PHONY : src/FileIO.cpp.s

src/HyperparametersCalculator.o: src/HyperparametersCalculator.cpp.o
.PHONY : src/HyperparametersCalculator.o

# target to build an object file
src/HyperparametersCalculator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phyDBSCAN.dir/build.make CMakeFiles/phyDBSCAN.dir/src/HyperparametersCalculator.cpp.o
.PHONY : src/HyperparametersCalculator.cpp.o

src/HyperparametersCalculator.i: src/HyperparametersCalculator.cpp.i
.PHONY : src/HyperparametersCalculator.i

# target to preprocess a source file
src/HyperparametersCalculator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phyDBSCAN.dir/build.make CMakeFiles/phyDBSCAN.dir/src/HyperparametersCalculator.cpp.i
.PHONY : src/HyperparametersCalculator.cpp.i

src/HyperparametersCalculator.s: src/HyperparametersCalculator.cpp.s
.PHONY : src/HyperparametersCalculator.s

# target to generate assembly for a file
src/HyperparametersCalculator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phyDBSCAN.dir/build.make CMakeFiles/phyDBSCAN.dir/src/HyperparametersCalculator.cpp.s
.PHONY : src/HyperparametersCalculator.cpp.s

src/poc.o: src/poc.cpp.o
.PHONY : src/poc.o

# target to build an object file
src/poc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phyDBSCAN.dir/build.make CMakeFiles/phyDBSCAN.dir/src/poc.cpp.o
.PHONY : src/poc.cpp.o

src/poc.i: src/poc.cpp.i
.PHONY : src/poc.i

# target to preprocess a source file
src/poc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phyDBSCAN.dir/build.make CMakeFiles/phyDBSCAN.dir/src/poc.cpp.i
.PHONY : src/poc.cpp.i

src/poc.s: src/poc.cpp.s
.PHONY : src/poc.s

# target to generate assembly for a file
src/poc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phyDBSCAN.dir/build.make CMakeFiles/phyDBSCAN.dir/src/poc.cpp.s
.PHONY : src/poc.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... phyDBSCAN"
	@echo "... src/ARI.o"
	@echo "... src/ARI.i"
	@echo "... src/ARI.s"
	@echo "... src/Clustering.o"
	@echo "... src/Clustering.i"
	@echo "... src/Clustering.s"
	@echo "... src/FileIO.o"
	@echo "... src/FileIO.i"
	@echo "... src/FileIO.s"
	@echo "... src/HyperparametersCalculator.o"
	@echo "... src/HyperparametersCalculator.i"
	@echo "... src/HyperparametersCalculator.s"
	@echo "... src/poc.o"
	@echo "... src/poc.i"
	@echo "... src/poc.s"
.PHONY : help

# The main run target
run: phyDBSCAN
	./phyDBSCAN

.PHONY: run

#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

